name = "PreCICE"
uuid = "57fbd4af-5cc3-4712-aac0-6930e7658184"
authors = ["preCICE <https://precice.org/> and contributors"]
version = "2.5.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
