name: Run Tests
on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: precice/precice
    strategy:
      matrix:
        julia-version: ['1.6.0','1.6.5','1.7.0','^1.7']
        julia-arch: [x64]
    
    steps:
      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}     
        
      - uses: actions/checkout@v2

      - name: Build Package
        uses: julia-actions/julia-buildpkg@v1

  run_tests:
    runs-on: ubuntu-latest
    container: precice/precice
    needs: [build]
    strategy:
      matrix:
        julia-version: ['1.6.0','1.6.5','1.7.0','^1.7']
        julia-arch: [x64, x86]
    
    steps:
      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}     
        
      - uses: actions/checkout@v2

      - name: Build Package
        uses: julia-actions/julia-buildpkg@v1

      - name: Run tests
        run: julia -e 'using Pkg; Pkg.test("PreCICE")'
        # uses: julia-actions/julia-runtest@v1
