name: Run Tests
on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1.6.0','1.6.5','1.7.0','^1.7']
        julia-arch: [x64, x86]
    
    steps:
      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}     

      - uses: actions/checkout@v2

      - name: Build Package
        uses: julia-actions/julia-buildpkg@v1

  run_tests:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        julia-version: ['1.6.0','1.6.5','1.7.0','^1.7']
        julia-arch: [x64, x86]
    
    steps:
      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}  
   
      - uses: precice/setup-precice-action@testing # needs to be changed to main after merge
        with:
          precice-version: 'v2.5.0' # needs to be changed to develop

      - uses: actions/checkout@v3

      - name: Build Package
        uses: julia-actions/julia-buildpkg@v1

      - name: install make
        run: |
         sudo apt update
         sudo apt install make

      - name: Build fake Solverinterface
        run: |
          cd test
          make
          echo $PATH
          echo $GITHUB_WORKSPACE
          echo $LD_LIBRARY_PATH

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Test Logs
          path: /home/runner/
          retention-days: 1

      - name: Run tests
        uses: julia-actions/julia-runtest@v1


      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Test Logs
          path: /home/runner/
          retention-days: 1
