name: Run Tests
on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ['1.6.0','1.6.5','1.7.0','^1.7']
        julia-arch: [x64, x86]
    
    steps:
      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}     
       
      - uses: precice/setup-precice-action
        with:
          precice-version: 'develop'

      - uses: actions/checkout@v2

      - name: Build Package
        uses: julia-actions/julia-buildpkg@v1

  run_tests:
    runs-on: ubuntu-latest
    container: precice/precice
    needs: [build]
    strategy:
      matrix:
        julia-version: ['1.6.0','1.6.5','1.7.0','^1.7']
        julia-arch: [x64, x86]
    
    steps:
      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}     
        
      - uses: actions/checkout@v2

      - name: Build Package
        uses: julia-actions/julia-buildpkg@v1

      - name: install make
        run: |
         apt update
         apt install make

      - name: Build Fake Solverinterface
        run: |
          cd test
          make

      - name: Run tests
        uses: julia-actions/julia-runtest@v1
