name: Run Tests
on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ['1.6.0','1.6.5','1.7.0','^1.7']
        julia-arch: [x64, x86]
    
    steps:
      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}     
        
      - uses: actions/setup-python@v1
      - name: Install OpenMPI, CMake, Boost library, Eigen and pkg-config
        run: |
          sudo apt-get -yy update
          sudo apt-get install -y libopenmpi-dev cmake libboost-all-dev libeigen3-dev pkg-config
          sudo rm -rf /var/lib/apt/lists/*

      - name: Checkout precice and make required files discoverable
        run: |
          git clone https://github.com/precice/precice.git precice
          cd precice
          mkdir build && cd build
          cmake .. -DPRECICE_MPICommunication=OFF -DPRECICE_PETScMapping=OFF -DPRECICE_PythonActions=OFF -DBUILD_TESTING=OFF
          make -j $(nproc)
          export LD_LIBRARY_PATH=$PWD:$LD_LIBRARY_PATH
          cd
      
      - uses: actions/checkout@v2

      - name: Build Package
        uses: julia-actions/julia-buildpkg@v1

      - name: Test Installation
        run:  julia -e "using PreCICE; println(PreCICE.getVersionInformation())" 

  run_tests:
    runs-on: ubuntu-latest
    container: precice/precice
    needs: [build]
    strategy:
      matrix:
        julia-version: ['1.6.0','1.6.5','1.7.0','^1.7']
        julia-arch: [x64, x86]
    
    steps:
      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}     
        
      - uses: actions/checkout@v2

      - name: Build Package
        uses: julia-actions/julia-buildpkg@v1

      - name: install make
        run: |
         apt update
         apt install make

      - name: Build Fake Solverinterface
        run: |
          cd test
          make

      - name: Run tests
        uses: julia-actions/julia-runtest@v1
