name: Run Tests
on: # run on every push to main and develop, and on every pull request to main and develop
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    container: precice/precice:develop
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1.6.0','1.6.5','1.7.0','^1.7']
        julia-arch: [x64, x86]
    
    steps:
      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}     

      - uses: actions/checkout@v2

      - name: Build Package
        uses: julia-actions/julia-buildpkg@v1

  run_tests:
    runs-on: ubuntu-latest
    container: precice/precice:develop
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1.6.0','1.6.5','1.7.0','^1.7']
        julia-arch: [x64, x86]
    
    steps:
      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}  
   
      - uses: actions/checkout@v3

      - name: Build Package
        uses: julia-actions/julia-buildpkg@v1

      - name: Build fake Solverinterface
        run: |
          cd test
          make
          echo $LD_LIBRARY_PATH
          echo $LIBRARY_PATH
          echo $PATH
          ldconfig -p | grep libprecice
          find /lib* /usr/lib* -name 'libprecice.so*'

      - name: Run tests
        uses: julia-actions/julia-runtest@v1
