name: Build PreCICE.jl
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Julia 1.6.1
        uses: julia-actions/setup-julia@v1.6.1
        with:
          version: 1.6.1
         
      - run: julia -e 'println("Julia installed successfully!")'
      - uses: actions/checkout@v2
      
      - name: Cache preCICE
        id: cache-libprecice
        uses: actions/cache@v2
        with:
          path: libprecice2_2.3.0_focal.deb
          key: libprecice2_2.3.0_focal.deb1
          restore-keys: libprecice2_2.3.0_focal.deb1
      
      - name: Download preCICE
        if: steps.cache-libprecice.outputs.cache-hit != 'true'
        run: wget https://github.com/precice/precice/releases/download/v2.3.0/libprecice2_2.3.0_focal.deb

      - name: Install preCICE
        run: sudo apt install ./libprecice2_2.3.0_focal.deb

      - name: Build Package
        uses: julia-actions/julia-buildpkg@v1