name: Run Tests
on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    container: precice/precice
    
    steps:

      - name: Install Julia 1.6.1
        uses: julia-actions/setup-julia@v1.6.1
        with:
          version: 1.6.1         
        
      - uses: actions/checkout@v2

      - name: Build Package
        uses: julia-actions/julia-buildpkg@v1

      - name: Run tests
        uses: julia-actions/julia-runtest@v1