name: Building package on the latest Julia version and on the latest Julia version under development 'nightly'
on: 
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  version_test:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest]
        julia-version: ['1.10.0', 'nightly']

    steps:
      - name: Update System
        run: sudo apt update

      - name: Install Julia version
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}         
      - uses: actions/checkout@v2
        

      - name: Cache preCICE
        id: cache-libprecice
        uses: actions/cache@v2
        with:
          path: libprecice3_3.1.0_focal.deb
          key: libprecice3_3.1.0_focal.deb1
          restore-keys: libprecice3_3.1.0_focal.deb1
      
      - name: Download preCICE
        if: steps.cache-libprecice.outputs.cache-hit != 'true'
        run: wget https://github.com/precice/precice/releases/download/v3.1.0/libprecice3_3.1.0_focal.deb

      - name: Install preCICE
        run: sudo apt install ./libprecice3_3.1.0_focal.deb

      - name: Build Package
        uses: julia-actions/julia-buildpkg@v1

      - name: Run tests
        uses: julia-actions/julia-runtest@v1
